spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://generator:generator@localhost:27017/generator?authSource=admin
  freemarker:
    cache: false
    suffix: .html
    content-type: text/html
    ##静态资源
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
server:
  port: 8888
  servlet:
    context-path:
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: trace