spring:
  data:
    mongodb:
      host: 127.0.0.1
      password: 123456
      port: 27017
      username: generator
      database: generator
  freemarker:
    cache: false
    suffix: .html
    content-type: text/html
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
server:
  port: 8888
  servlet:
    context-path:
